### ISSUE TITLE
TypeError on graphyte 

### ISSUE THREAD

**Issue by sjairam** [rixka/graphite-client#2]
hi

We on bpftrace 0.9.4, we getting an error on the python script.

Please see below:
root@ip-172-31-36-21:~# ./graphite_client.py -f /var/log/cpu-lat.log -m bpftrace
Running graphite client... Hit Ctrl-C to end.
Traceback (most recent call last):
  File "./graphite_client.py", line 118, in <module>
    main()
  File "./graphite_client.py", line 22, in main
    capture_and_ship(args)
  File "./graphite_client.py", line 64, in capture_and_ship
    client.send(parsed_values[0], parsed_values[-1])
  File "./graphite_client.py", line 93, in send
    graphyte.send(bucket, value)
  File "/root/graphyte.py", line 203, in send
    default_sender.send(*args, **kwargs)
  File "/root/graphyte.py", line 103, in send
    message = self.build_message(metric, value, timestamp, tags)
  File "/root/graphyte.py", line 76, in build_message
    raise TypeError('"value" must be an int or a float, not a {}'.format(
TypeError: "value" must be an int or a float, not a str

**Comment by sjairam** [comment]
root@ip-172-31-36-21:~# date
Fri Dec  9 15:09:51 UTC 2022
root@ip-172-31-36-21:~# bpftrace --version
bpftrace v0.9.4

Date and version
